# Generated by Django 3.2.7 on 2021-09-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('pair', models.CharField(max_length=100, verbose_name='pair')),
                ('time', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='time')),
                ('trade_type', models.CharField(max_length=100, verbose_name='type')),
                ('order_type', models.CharField(max_length=100, verbose_name='order_type')),
                ('price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='price')),
                ('cost', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='cost')),
                ('fee', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='fee')),
                ('vol', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='vol')),
                ('margin', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='margin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users')),
            ],
            options={
                'db_table': 'trades',
                'managed': True,
            },
        ),
    ]
