# Generated by Django 3.2.7 on 2021-09-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.CharField(default='0', max_length=100, verbose_name='balance'),
        ),
    ]
