# Generated by Django 3.2.7 on 2021-09-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_users_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='balance'),
        ),
    ]
